# FILENAME
# configure_interfaces_dns.yml
#
# DESCRIPTION
# Sample playbook used for AWS Automation webinar
#
# REQUIREMENTS
# pip install ansible
# ansible-galaxy install PaloAltoNetworks.paloaltonetworks
# create vars.yml and configure with your credentials (vars-sample.yml file provided)
#
# EXECUTE
# ansible-playbook configure_interfaces_dns.yml
---
- hosts: localhost
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
    - name: include variables (free-form)
      include_vars: vars.yml
      no_log: 'yes'

    - name: configure ethernet1/1
      panos_interface:
        ip_address: "{{mgmt_ip}}"
        username: "{{admin_username}}"
        password: "{{admin_password}}"
        ip_address: "{{mgmt_ip}}"
        if_name: "ethernet1/1"
        zone_name: "untrust"
        create_default_route: "yes"
        commit: False

    - name: configure ethernet1/2
      panos_interface:
        ip_address: "{{mgmt_ip}}"
        username: "{{admin_username}}"
        password: "{{admin_password}}"
        if_name: "ethernet1/2"
        zone_name: "trust"
        create_default_route: "no"
        commit: False

    - name: set dns and ntp
      panos_mgtconfig:
        ip_address: "{{mgmt_ip}}"
        username: "{{admin_username}}"
        password: "{{admin_password}}"
        dns_server_primary: "8.8.8.8"
        ntp_server_primary: "0.us.pool.ntp.org"
        ntp_server_secondary: "1.us.pool.ntp.org"
        timezone: "US/Pacific"
        login_banner: "Secure environment"
        commit: True

