# FILENAME
# create_secuirty_policies.yml
#
# DESCRIPTION
# Sample playbook used for AWS Automation webinar
#
# REQUIREMENTS
# pip install ansible
# ansible-galaxy install PaloAltoNetworks.paloaltonetworks
# create vars.yml and configure with your credentials (vars-sample.yml file provided)
#
# EXECUTE
# ansible-playbook create_security_policies.yml
---
- hosts: localhost
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
    - name: include variables (free-form)
      include_vars: vars.yml
      no_log: 'yes'

    - name: add a rule to allow HTTP
      panos_security_rule:
        ip_address: "{{ mgmt_ip }}"
        username: "{{ admin_username }}"
        password: "{{admin_password}}"
        operation: 'add'
        rule_name: 'Web traffic'
        application: 'web-browsing'
        description: 'Allow HTTP traffic'
        source_zone: ['untrust']
        destination_zone: ['trust']
        action: 'allow'
        commit: "False"

    - name: SSH Inbound
      panos_security_rule:
        ip_address: "{{ mgmt_ip }}"
        username: "{{ admin_username }}"
        password: "{{admin_password}}"
        operation: 'add'
        rule_name: 'SSH traffic'
        application: ['ping','ssh']
        description: 'Allow SSH traffic'
        source_zone: ['untrust']
        destination_zone: ['trust']
        action: 'allow'
        commit: "False"

    - name: SSH 221 Inbound
      panos_security_rule:
        ip_address: "{{ mgmt_ip }}"
        username: "{{ admin_username }}"
        password: "{{admin_password}}"
        operation: 'add'
        rule_name: 'SSH 221 traffic'
        application: ['ping','ssh']
        service: 'service-tcp-221'
        description: 'Allow SSH traffic'
        source_zone: ['untrust']
        destination_zone: ['trust']
        action: 'allow'
        commit: "False"

    - name: allow all rule 
      panos_security_rule:
        ip_address: "{{ mgmt_ip }}"
        username: "{{ admin_username }}"
        password: "{{admin_password}}"
        operation: 'add'
        rule_name: 'allow-out-all'
        application: 'any'
        description: 'allow all outbound'
        source_zone: ['trust']
        destination_zone: ['untrust']
        action: 'allow'
        commit: "False"

    - name: Log default deny
      panos_security_rule:
        ip_address: "{{ mgmt_ip }}"
        username: "{{ admin_username }}"
        password: "{{admin_password}}"
        operation: 'add'
        rule_name: 'Log default deny'
        description: 'Allow SSH traffic'
        source_zone: ['untrust']
        destination_zone: ['trust']
        action: 'deny'
        commit: "True"
