---
- name: Add some address groups to the firewall
  hosts: my-firewall
  connection: local
  gather_facts: False

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'firewall-secrets.yml'
    no_log: 'yes'

  - name: Create static address group
    panos_address_group_object:
      ip_address: '{{ fw_ip_address }}'
      username: '{{ fw_username }}'
      password: '{{ fw_password }}'
      name: 'Prod-Instances'
      static_value: ['Test-1.1.1.1', 'Test-2.2.2.2', 'Test-3.3.3.3']
      tag: ['Prod']

  - name: Create dynamic address group
    panos_address_group_object:
      ip_address: '{{ fw_ip_address }}'
      username: '{{ fw_username }}'
      password: '{{ fw_password }}'
      name: 'SI-Web-EPG'
      dynamic_value: 'SI-Web-EPG'
      tag: ['SI']

  - name: Delete address group
    panos_address_group_object:
      ip_address: '{{ fw_ip_address }}'
      username: '{{ fw_username }}'
      password: '{{ fw_password }}'
      name: 'Old-Prod-Instances'
      state: 'absent'