- hosts: my-firewall
  connection: local
  gather_facts: False

#  roles:
#    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'firewall-secrets.yml'
    no_log: 'yes'

  - name: Delete IKE gateway config from the firewall
    panos_ike_gateway:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      state: 'absent'
      name: 'IKEGW-Ansible'
      commit: 'False'
