- hosts: my-firewall
  connection: local
  gather_facts: False

#  roles:
#    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'firewall-secrets.yml'
    no_log: 'yes'

  - name: Delete named IKE crypto profile
    panos_ike_crypto_profile:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      state: 'absent'
      name: 'IKE-Ansible'
      commit: 'False'
