- name: Set basic FW mgmt plumbing
  hosts: my-firewall
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  vars:
    dns_server_primary: "1.1.1.1"
    dns_server_secondary: "1.1.1.2"
    panorama_primary: "1.1.1.3"
    panorama_secondary: "1.1.1.4"
    ntp_server_primary: "1.1.1.5"
    ntp_server_secondary: "1.1.1.6"
    timezone: "US/Central"
    update_server: "update.me"
    login_banner: "Secure environment"

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'firewall-secrets.yml'
    no_log: 'yes'

  - name: set dns, ntp, and panorama but don't commit
    panos_mgtconfig:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"
      dns_server_primary: "{{ dns_server_primary }}"
      dns_server_secondary: "{{ dns_server_secondary }}"
      panorama_primary: "{{ panorama_primary }}"
      panorama_secondary: "{{ panorama_secondary }}"
      ntp_server_primary: "{{ ntp_server_primary }}"
      ntp_server_secondary: "{{ ntp_server_secondary }}"
      timezone: "{{ timezone }}"
      update_server: "{{ update_server }}"
      login_banner: "{{ login_banner }}"
      commit: False
