- name: Configure Redistribution Profile
  hosts: my-firewall
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  vars:
    ip_address: '{{ ansible_host }}'

  tasks:
    - name: Grab the credentials from ansible-vault
      include_vars: 'firewall-secrets.yml'
      no_log: 'yes'

    - name: Create Redistribution Profile
      panos_redistribution:
        ip_address: '{{ ip_address }}'
        username: '{{ username }}'
        password: '{{ password }}'
        vr_name: default
        name: redist-01
        priority: 10
        filter_type:
          - static
          - rip

    - name: Remove Redistribution Profile
      panos_redistribution:
        ip_address: '{{ ip_address }}'
        username: '{{ username }}'
        password: '{{ password }}'
        state: absent
        vr_name: default
        name: redist-01
