---
- name: Manipulate registered IPs on the firewall
  hosts: my-firewall
  connection: local
  gather_facts: False

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'firewall-secrets.yml'
    no_log: 'yes'

  - name: Add 'First_Tag' tag to 1.1.1.1 and 1.1.1.2
    panos_registered_ip:
      ip_address: '{{ fw_ip_address }}'
      username: '{{ fw_username }}'
      password: '{{ fw_password }}'
      ips: ['1.1.1.1', '1.1.1.2']
      tags: ['First_Tag']
      state: 'present'

  - name: Add 'Second_Tag' tag to 1.1.1.1
    panos_registered_ip:
      ip_address: '{{ fw_ip_address }}'
      username: '{{ fw_username }}'
      password: '{{ fw_password }}'
      ips: ['1.1.1.1']
      tags: ['Second_Tag']
      state: 'present'

  - name: Remove 'Second_Tag' from 1.1.1.1
    panos_registered_ip:
      ip_address: '{{ fw_ip_address }}'
      username: '{{ fw_username }}'
      password: '{{ fw_password }}'
      ips: ['1.1.1.1']
      tags: ['Second_Tag']
      state: 'absent'

  - name: Remove 'First_Tag' from 1.1.1.2 (will unregister entirely)
    panos_registered_ip:
      ip_address: '{{ fw_ip_address }}'
      username: '{{ fw_username }}'
      password: '{{ fw_password }}'
      ips: ['1.1.1.2']
      tags: ['First_Tag']
      state: 'absent'