- name: Add some security rules to the firewall
  hosts: my-firewall
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'firewall-secrets.yml'
    no_log: 'yes'

  - name: Create route 'Test-One'
    panos_static_route:
      ip_address: '{{ fw_ip_address }}'
      username: '{{ fw_username }}'
      password: '{{ fw_password }}'
      name: 'Test-One'
      destination: '1.1.1.0/24'
      nexthop: '10.0.0.1'

  - name: Create route 'Test-Two'
    panos_static_route:
      ip_address: '{{ fw_ip_address }}'
      username: '{{ fw_username }}'
      password: '{{ fw_password }}'
      name: 'Test-Two'
      destination: '2.2.2.0/24'
      nexthop: '10.0.0.1'

  - name: Create route 'Test-Three'
    panos_static_route:
      ip_address: '{{ fw_ip_address }}'
      username: '{{ fw_username }}'
      password: '{{ fw_password }}'
      name: 'Test-Three'
      destination: '3.3.3.0/24'
      nexthop: '10.0.0.1'

  - name: Delete route 'Test-Two'
    panos_static_route:
      ip_address: '{{ fw_ip_address }}'
      username: '{{ fw_username }}'
      password: '{{ fw_password }}'
      name: 'Test-Two'
      state: 'absent'

- name: Create route 'Test-Four'
  panos_static_route:
    ip_address: '{{ fw_ip_address }}'
    username: '{{ fw_username }}'
    password: '{{ fw_password }}'
    name: 'Test-Four'
    destination: '4.4.4.0/24'
    nexthop: '10.0.0.1'
    virtual_router: 'VR-Two'
