- name: Make sure the given user is present and has the specified password
  hosts: my-panorama
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'panorama-secrets.yml'
    no_log: 'yes'

  - name: 'Admin "joe" as a device admin administrator'
    panos_admin:
      ip_address: '{{ ip_address }}'
      password: '{{ password }}'
      admin_username: 'joe'
      admin_password: 'secret'
      device_admin: true
      commit: false
